services:    # differents services (images)

# --- La data base (mariaDB)
  mariadb:
    image: mariadb:42
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

# --- Le site internet (wordpress) ---
  wordpress:
    image: wordpress:42
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: on-failure

# --- Bonus : Redis Cache ---
  redis:
    image: bonus-redis:42
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

# --- Bonus : Static Website ---
  website:
    image: bonus-website:42
    container_name: website
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    networks:
      - inception
    restart: on-failure

# --- Bonus : Adminer ---
  adminer:
    image: bonus-adminer:42
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    restart: on-failure

# --- Bonus : Portainer ---
  portainer:
    image: bonus-portainer:42
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Donner acces au docker a la VM
      - portainer_data:/data
    networks:
      - inception
    restart: on-failure

# --- Le gardien la securite (NGINX) ---
  nginx:
    image: nginx:42
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  wordpress_data:
    driver: local # on stocke le volume en local
    driver_opts:
      type: 'none'
      o: 'bind' # --> Ne cree pas un nouveau systeme de fichier, fait un 'miroir' (bind mount) dun dossier existant
      device: /home/mariosrb/data/wordpress
  mariadb_data:
    driver: local # on stocke le volume en local
    driver_opts:
      type: 'none'
      o: 'bind' # --> Ne cree pas un nouveau systeme de fichier, fait un 'miroir' (bind mount) dun dossier existant
      device: /home/mariosrb/data/mariadb
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/mariosrb/data/portainer

networks:
  inception:
    driver: bridge
